services:
  db:
    image: postgres:17
    container_name: war-weeker-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: war_weeker
    ports:
      - "2345:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
